# Generated by Django 3.2.8 on 2021-11-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10000)),
                ('book_name', models.CharField(max_length=10000)),
                ('publication_name', models.CharField(max_length=10000, null=True)),
                ('book_edition', models.CharField(max_length=10000, null=True)),
            ],
        ),
    ]
