# Generated by Django 3.2.8 on 2021-11-10 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='book_edition',
            new_name='edition',
        ),
    ]
