# Generated by Django 3.2.8 on 2021-11-06 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211101_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='rental_plan',
        ),
    ]
