# Generated by Django 3.2.8 on 2021-11-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20211106_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rental_period',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
