# Generated by Django 3.2.8 on 2021-11-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20211107_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='thumbnail',
            field=models.CharField(default=' ', max_length=2000000000),
            preserve_default=False,
        ),
    ]
